version: '3.4'

services:
  freakyfashionservices.catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  freakyfashionservices.basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashionservices.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashionservices.pricecatalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashionservices.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

