version: '3.4'

services:
  freakyfashionservices.catalog:
    image: ${DOCKER_REGISTRY-}freakyfashionservicescatalog
    build:
      context: .
      dockerfile: FreakyFashionServices.Catalog/Dockerfile

  freakyfashionservices.basket:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesbasket
    build:
      context: .
      dockerfile: FreakyFashionServices.Basket/Dockerfile


  freakyfashionservices.gateway:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesgateway
    build:
      context: .
      dockerfile: FreakyFashionServices.Gateway/Dockerfile


  freakyfashionservices.pricecatalog:
    image: ${DOCKER_REGISTRY-}freakyfashionservicespricecatalog
    build:
      context: .
      dockerfile: FreakyFashionServices.PriceCatalog/Dockerfile


  freakyfashionservices.order:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesorder
    build:
      context: .
      dockerfile: FreakyFashionServices.Order/Dockerfile

